---
title: "Friday 3/26"
author: "Sarah Brashear"
date: "3/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
data(mpg)
data(ToothGrowth)
```

```{r}

ggplot(data = mpg,
       aes(x = displ, y = hwy, col = class)) +
  geom_point()
```

```{r}

# This creates the same plot.
# You could specify x, y, col within the aesthetic argument if you're using
# multiple layers with different arguments.

ggplot(data = mpg) +
  geom_point(aes(x = displ, y = hwy, col = class))
```


```{r}

ggplot(data = mpg,
       aes(x = displ, y = hwy, col = class, pch = fl)) +
  geom_point()

```


```{r}

ggplot(data = mpg,
       aes(x = cty, y = hwy, size = cyl)) +
  geom_point()

```

```{r}

ggplot(data = mpg, aes(y = hwy, col = class)) +
  geom_point(aes(x = displ), pch = 15) +
  geom_point(aes(x = cty), pch = 17)
```


```{r}

ToothGrowth$dose <- as.factor(ToothGrowth$dose)

ggplot(data = ToothGrowth, 
       aes(x = dose, y = len, group = dose)) +
  geom_boxplot()

```


```{r}

ggplot(data = ToothGrowth, 
       aes(x = dose, y = len)) +
  geom_boxplot(col = "blue") +
  geom_point(col = "red")

```

